@startuml DriveHub - Reservas

title Solicitud de Reservas

Cliente -> SistemaEmpresa: Solicitar reserva
SistemaEmpresa -> SistemaEmpresa: Validar disponibilidad
SistemaEmpresa -> GestorReserva: Crear reserva
SistemaEmpresa <- GestorReserva: Añadir reserva
Cliente <- SistemaEmpresa: Confirmar reserva

@enduml