@startuml DriveHub

title TP - Programacion 2 - DriveHub


class SistemaEmpresa {
    - vehiculos: Vehiculo[]
    - reservas: Reserva[]
    - gestorReserva: GestorReserva
    - gestorVehiculo: GestorVehiculo
    - gestorMantenimiento: GestorMantenimiento
    - gestorKilometraje: GestorKilometraje
    - gestorEstadisticas: GestorEstadisticas
    + realizarReserva(vehiculo: Vehiculo, cliente: Cliente, fechaInicio: Date, fechaFin: Date): Reserva | null
    + cancelarReserva(reserva: Reserva): void
    + agregarVehiculo(v: Vehiculo): void
    + eliminarVehiculo(v: Vehiculo): void
    + alquilar(vehiculo: Vehiculo): void
}

class Reserva {
    - kmsRecorridos: number
    - vehiculo: Vehiculo
    - cliente: Cliente
    - fechaInicio: Date
    - fechaFin: Date
    - temporada: Temporada
    + calcularTotal(): number
    + validarFecha(): boolean
    + getDias(): number
}

class Cliente {
    - nombreCompleto: string
    - id: number
    + solicitarReserva(fechaInicio: Date, fechaFin: Date, vehiculo: Vehiculo, sistema: SistemaEmpresa): void  
}

'Herencia Vehiculo a sus clases hijas
abstract class Vehiculo {
    - tarifaBase: number
    - cargoVariable: number
    - cargoFijo: number
    - kilometraje: number
    - matricula: string
    - estado: Estado
    - mantenimientos: MantenimientoVehiculo[]
    + agregarMantenimientoVehiculo(mantenimiento: MantenimientoVehiculo): void
    + abstract calcCargoVariable(kmsRecorridos: number): number
    + requiereMantenimiento(): boolean
    + resetearKm(): void
    + alquilar(): void
    + devolver(): void
    + enviarAMantenimiento(): void
    + finalizarMantenimiento(): void
    + enviarAlimpiar(): void
    + finalizarLimpieza(): void
    + getCostoTotalMantenimiento(): number
}

class Compacto {
    + calcCargoVariable(kmsRecorridos: number): number
}

class Sedan {
    + calcCargoVariable(kmsRecorridos: number): number
}

class Suv {
    + calcCargoVariable(kmsRecorridos: number): number
}

'Atributo del vehiculo
class MantenimientoVehiculo {
    - costoMantenimiento: number
    - fecha: Date
}

class GestorVehiculo {
    + buscarVehiculo(matricula: string, lista: Vehiculo[]): Vehiculo
    + agregar<T>(item: T, lista: Array<T>): void
    + eliminar<T>(item: T, lista: Array<T>): void
}

'Implementacion del patro state para el estado del vehiculo
interface Estado{
    + alquilar (): void
    + devolver(): void
    + enviarAMantenimiento(): void
    + finalizarMantenimiento(): void
    + enviarAlimpiar(): void
    + finalizarLimpieza(): void
}

class Disponible {
    - vehiculo: Vehiculo
    + setVehiculo(vehiculo: Vehiculo):void
    + alquilar (): void
    + devolver(): void
    + enviarAMantenimiento(): void
    + finalizarMantenimiento(): void
    + enviarAlimpiar(): void
    + finalizarLimpieza(): void
}

class EnAlquiler {   
    - vehiculo: Vehiculo
    + setVehiculo(vehiculo: Vehiculo):void
    + alquilar (): void
    + devolver(): void
    + enviarAMantenimiento(): void
    + finalizarMantenimiento(): void
    + enviarAlimpiar(): void
    + finalizarLimpieza(): void
}

class EnMantenimiento {
    - vehiculo: Vehiculo
    + setVehiculo(vehiculo: Vehiculo):void
    + alquilar (): void
    + devolver(): void
    + enviarAMantenimiento(): void
    + finalizarMantenimiento(): void
    + enviarAlimpiar(): void
    + finalizarLimpieza(): void
}

class NecesitaLimpieza {
    - vehiculo: Vehiculo
    + setVehiculo(vehiculo: Vehiculo):void
    + alquilar (): void
    + devolver(): void
    + enviarAMantenimiento(): void
    + finalizarMantenimiento(): void
    + enviarAlimpiar(): void
    + finalizarLimpieza(): void
}

class GestorReserva {
    + hayDisponibilidad(fechaInicio: Date, fechaFin: Date, vehiculo: Vehiculo, reservas: Reserva[]): boolean  
    + agregar(reserva: Reserva, reservas: Reserva[]): void
    + eliminar(reserva: Reserva, reservas: Reserva[]): void
}

class GestorKilometraje {
    + actualizarKmVehiculo(reserva: Reserva, sistema: SistemaEmpresa): void
}

class GestorMantenimiento {
    + registrarMantenimiento(v: Vehiculo, m: Mantenimiento): void  
}

class GestorEstadisticas {
    - filtrarReservasPorFecha(reservas: Reserva[], fechaInicio: Date, fechaFin: Date): Reserva[]
    + getRankingAlquileres(historial: Reserva[], fechaInicio: Date, fechaFin: Date): void
    + getRentabilidad(vehiculos: Vehiculo[], historial: Reserva[]): void
    + ocupacionFlota(vehiculos: Vehiculo[]): number
}

interface ABM {
    agregar<T>(item: T, lista: Array<T>): void
    eliminar<T>(item: T, lista: Array<T>): void
}

interface Temporada {
    calcTarifaBase(tarifa: number): number
}

class TempAlta {
    + calcTarifaBase(tarifa: number): number
}

class TempMedia {
    + calcTarifaBase(tarifa: number): number
}

class TempBaja {  
    + calcTarifaBase(tarifa: number): number
}

'Relaciones:

'Herencia
Vehiculo <|-- Sedan
Vehiculo <|-- Suv
Vehiculo <|-- Compacto

'Atributos de vehiculo
Vehiculo --> MantenimientoVehiculo
Vehiculo *-r- Estado

'Composición
Reserva *-r- Cliente
Reserva *-- Vehiculo
Reserva *-- Temporada

SistemaEmpresa *-- Vehiculo
SistemaEmpresa *-- Reserva
SistemaEmpresa *-- GestorReserva
SistemaEmpresa *-r- GestorKilometraje
SistemaEmpresa *-u- GestorMantenimiento
SistemaEmpresa *-l- GestorVehiculo
SistemaEmpresa *-- GestorEstadisticas

'Implementacion interfaces:
ABM <|.u. GestorReserva
ABM <|.u. GestorVehiculo

Temporada <|.. TempAlta
Temporada <|.. TempMedia
Temporada <|.. TempBaja

Disponible .d.|> Estado
EnAlquiler ..|> Estado
EnMantenimiento .l.|> Estado
NecesitaLimpieza .u.|> Estado


@enduml